### ISSUE TITLE
Option to only display chosen Pollen-type(s).

### ISSUE THREAD

**Issue by lxne** [carstendirks/MMM-DWD-Pollen#1]
Hi, I recently switched from [MMM-pollen](https://github.com/devduisburg/MMM-pollen) to this module, because MMM-pollen is not able to receive data anymore. There was only one feature why I preferred the other module: One could choose which Pollen alarms should be shown (in my case only 'Graeser').

Is it difficult to implement such a feature?

**Comment by carstendirks** [comment]
No - I think this is easy. Let me try.

**Comment by lxne** [comment]
> No - I think this is easy. Let me try.

Awesome! Thank you very much.
