### ISSUE TITLE
No data after updating. Shows only "Lade…"

### ISSUE THREAD

**Issue by lxne** [carstendirks/MMM-DWD-Pollen#10]
After updating today with 'git pull' I am not getting any data anymore. I tried deleting the module folder and reinstalling it, but that didn't change anything.

In the logs I get:
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at checkData (MMM-DWD-Pollen.js:173:24)
    at MMM-DWD-Pollen.js:201:34
    at Array.forEach (<anonymous>)
    at MMM-DWD-Pollen.js:201:14
    at Array.forEach (<anonymous>)
    at Class.getDom (MMM-DWD-Pollen.js:192:27)
    at main.js:113:35
    at new Promise (<anonymous>)
    at updateDom (main.js:111:10)
    at Object.updateDom (main.js:552:4)

My config part looks like:

> module: "MMM-DWD-Pollen",
       		disabled: false,
       		position: "top_right",
		header: "Pollen",
		config: {
			updateinterval: 3.34 * 60 * 60 * 1000,
			DWD_Region: 92,
			icon: false,
			showNullValue: false, //Show value or symbol if value is 0
		}

Any idea what the problem could be?

Out of curiosity I tried https://github.com/vincep5/MMM-Pollen, which stopped working some time ago. It is functional again.

Best regards

**Comment by carstendirks** [comment]
you are missing something in your config, try adding:

`pollenList: "Hasel,Erle,Esche,Birke,Graeser,Roggen,Beifuss,Ambrosia",'

**Comment by lxne** [comment]
Oh boy. Thank you.
This wasn't mandatory before, was it?
Because it worked with that config before I updated.

Thanks again.
