### ISSUE TITLE
Day after tomorrow

### ISSUE THREAD

**Issue by nkl-kst** [carstendirks/MMM-DWD-Pollen#11]
Hi Carsten,

is there a reason why the data for the day after tomorrow is not used and displayed? It's available in the DWD-JSON.

Thanks in advance.

**Comment by carstendirks** [comment]
Hi,
no reasons I only saw it today when you mentioned it. Either it was not there when I did the initial development or I did not recognize it. I can enhance to show all 3 values!
Thanks

**Comment by carstendirks** [comment]
Changed code, published new to master. Please see whether it fits.

**Comment by nkl-kst** [comment]
Works as expected! Thanks for the fast implementation 👍
