### ISSUE TITLE
wrong values for day after tomorrow

### ISSUE THREAD

**Issue by utzl** [carstendirks/MMM-DWD-Pollen#12]
Hi,

I just ran the update you provided.
See what I got now :-) 
![Unbenannt](https://github.com/carstendirks/MMM-DWD-Pollen/assets/86625839/b9b9f087-68d5-4ba5-84ba-966f9933d2be)

my config file:
```
{
	module: "MMM-DWD-Pollen",
	position: "top_center",
	classes: 'daytime_scheduler',
	header: "Pollenvorhersage",
	config: {
		updateInterval: 1 * 60 * 60 * 1000, // every hour
		DWD_region: 92, // Rhein Main
		icon: false, 
		pollenList: "Hasel,Erle,Esche,Birke,Graeser,Roggen,Beifuss,Ambrosia", 
		showNullValue: false
	}
},
```
Thanks

**Comment by carstendirks** [comment]
Wonderful :-)
Just did a fix, can you try it again?

**Comment by utzl** [comment]
Great.
Now it works as it should.
Thanks!

**Comment by carstendirks** [comment]
Thanks.
That bug was introduced when expanding to three days. Thanks for spotting.
