### ISSUE TITLE
Little mistake in the configuration

### ISSUE THREAD

**Issue by iot-werkstatt** [carstendirks/MMM-DWD-Pollen#2]
Hi Carsten,

at first, great job! I like this module a lot and it is working like a charme.

One issue I found when copy paste the configuration from your documentation: There is on "}" missing after the config section. 

Maybe you can change it? ;-) 

Regards

Daniel

**Comment by carstendirks** [comment]
Good catch!! Thanks. Corrected.

**Comment by carstendirks** [comment]
Changed Readme
