### ISSUE TITLE
Show low-Icon for pollenValue "0" instead of "Keine Werte"

### ISSUE THREAD

**Issue by smurex** [carstendirks/MMM-DWD-Pollen#3]
Hi,

I like the idea of the module and wanted to try it out.
After the Installation I only received "Keine Werte" (no values available) and thought of an config- or script-error. But obviously the pollenValue "0" in the result is handled as if there were no data at all.
You might have already considered this case for textual presentation (https://github.com/carstendirks/MMM-DWD-Pollen/blob/master/MMM-DWD-Pollen.js#L91) but not for icons.
What do you think about showing the low-icon in this case?

**Comment by carstendirks** [comment]
Hi,
right - I had no idea for a symbol. What about "fa-star-o"?
<i class="fa fa-star-o" aria-hidden="true"></i>

**Comment by smurex** [comment]
Looks great.

**Comment by carstendirks** [comment]
committed it, give it a try

**Comment by carstendirks** [comment]
Inserted icon for 0

**Comment by smurex** [comment]
Unfortunately it still doesn't work. While checking the result, the script expects the values for today or tomorrow to be unequal to 0 (for example in line 168), only then pollenDataAvailable will be set. Check for >= 0?

**Comment by carstendirks** [comment]
Right. Should have tested this. I guess I have to make this configurable since not everybody wants to show null values.

**Comment by carstendirks** [comment]
Introduced a new config value "showNullValue". If set to true, shows also values that are 0.  Works with values and icons.

**Comment by smurex** [comment]
Works as expected. Thank you very much :)
