### ISSUE TITLE
Module installation fails due to missing package.json 

### ISSUE THREAD

**Issue by pinsdorf** [carstendirks/MMM-DWD-Pollen#7]
**Describe the bug**
When one does a clean install of your module, then the command `npm install` will fail **because of a missing file** `package.json`. This file contains meta-data required by `npm` to install dependency packages. 

The error message on the console after `npm install` looks like this:
```sh
pi@home:~/magic_mirror/modules/MMM-DWD-Pollen $ npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path ~/magic_mirror/modules/MMM-DWD-Pollen/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '~/magic_mirror/modules/MMM-DWD-Pollen/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-09-03T20_02_57_396Z-debug.log
```

Subequently, the magic mirror won't start due to missing package dependencies.  In the mirror's log file you'll find entries like this:
```log
magicmirror    | [03.09.2021 22:01.08.807] [ERROR] Error: Cannot find module 'request'
magicmirror    | Require stack:
magicmirror    | - /opt/magic_mirror/modules/MMM-DWD-Pollen/node_helper.js
magicmirror    | - /opt/magic_mirror/js/app.js
magicmirror    | - /opt/magic_mirror/serveronly/index.js
magicmirror    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
magicmirror    |     at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
magicmirror    |     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
magicmirror    |     at Module.require (internal/modules/cjs/loader.js:961:19)
magicmirror    |     at require (internal/modules/cjs/helpers.js:92:18)
magicmirror    |     at Object.<anonymous> (/opt/magic_mirror/modules/MMM-DWD-Pollen/node_helper.js:7:15)
magicmirror    |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
magicmirror    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
magicmirror    |     at Module.load (internal/modules/cjs/loader.js:937:32)
magicmirror    |     at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
magicmirror    |   code: 'MODULE_NOT_FOUND',
magicmirror    |   requireStack: [
magicmirror    |     '/opt/magic_mirror/modules/MMM-DWD-Pollen/node_helper.js',
magicmirror    |     '/opt/magic_mirror/js/app.js',
magicmirror    |     '/opt/magic_mirror/serveronly/index.js'
magicmirror    |   ]
magicmirror    | }
magicmirror    | [03.09.2021 22:01.08.808] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
magicmirror    | [03.09.2021 22:01.08.809] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
magicmirror    | copy default modules to host ...
magicmirror    | copy css files to host ...
magicmirror    | chown modules and config folder ...
magicmirror    | timezone is Europe/Berlin
magicmirror    | start magicmirror
```

**To Reproduce**
1.  remove any existing `modules/MMM-DWD-Pollen` installation, e.g. by renaming the directory. This is important since it will fail on a fresh install
2. follow the installation procedure as described in [README.md](https://github.com/carstendirks/MMM-DWD-Pollen/blob/master/README.md)
``` 
cd ~/MagicMirror/modules # adapt directory if you are using a different one
git clone https://github.com/carstendirks/MMM-DWD-Pollen.git
cd MMM-DWD-Pollen
npm install # this can take a while
```

**Expected behavior**
Command `npm install` succeeds and Magic Mirror starts without errors.

**Desktop (please complete the following information):**
 - OS: Linux home 5.10.52-v7+ #1441 SMP Tue Aug 3 18:10:09 BST 2021 armv7l GNU/Linux
 - Browser: chromium-browser
 - Version: Chromium 84.0.4147.141 Built on Raspbian , running on Raspbian 10

**Additional context**
As described above. Simply add your `package.json` to the repo. I can circumvent the problem to make my own `package.json`, e.g. with `npm init` and `npm add request`. The result looks like this:

```json
{
  "name": "mmm-dwd-pollen",
  "version": "1.0.0",
  "description": "This Magic Mirror² module display the Pollen information from DWD (=Deutscher Wetterdienst)",
  "main": "MMM-DWD-Pollen.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/carstendirks/MMM-DWD-Pollen.git"
  },
  "author": "carstendirks",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/carstendirks/MMM-DWD-Pollen/issues"
  },
  "homepage": "https://github.com/carstendirks/MMM-DWD-Pollen#readme",
  "dependencies": {
    "request": "^2.88.2"
  }
}
```

**Comment by carstendirks** [comment]
Thank you - you are right. I missed this.
Can you try it whether it works now?
Thanks!

**Comment by albertusQuelle** [comment]
It seems that i have a similar problem. 
Fresh install. That is the very first module and i get that error

![image](https://user-images.githubusercontent.com/2970225/132256437-2a7ae72e-bb0e-4933-9556-26e8508b148f.png)

**Comment by carstendirks** [comment]
I just tried it with a fresh install of the module (not a fresh install of MagicMirror), the package.json is now correctly installed and the MagicMirror starts w/o errors.

**Comment by pinsdorf** [comment]
Hi  @carstendirks, thanks for your quick fix.

I tried the instalation with a *fresh install* and it works like a charm.

Moreover, I tested it on my *previous installation*, which I had fixed with my own `package.json` as described in the issue. Here I had to remove the own `package.json` so that the `git pull` does not run into conflicts. But error of the git command is straightforward (see below).

```sh
pi@home:~/magic_mirror/modules/MMM-DWD-Pollen $ git pull
From https://github.com/carstendirks/MMM-DWD-Pollen
   83580c3..4e4a513  master     -> origin/master
Updating 83580c3..4e4a513
error: The following untracked working tree files would be overwritten by merge:
        package.json
Please move or remove them before you merge.
Aborting
pi@home:~/magic_mirror/modules/MMM-DWD-Pollen $ rm package.json
pi@home:~/magic_mirror/modules/MMM-DWD-Pollen $ git pull
Updating 83580c3..4e4a513
Fast-forward
 package.json | 19 +++++++++++++++++++
 1 file changed, 19 insertions(+)
 create mode 100644 package.json
pi@home:~/magic_mirror/modules/MMM-DWD-Pollen $ npm install

removed 47 packages, and audited 1 package in 3s

found 0 vulnerabilities
```

I'm closing this issue. Thanks again!

**Comment by pinsdorf** [comment]
Oh, one more comment. I just looked at  your `package.json` and was surprised that it does not contain an entry like:

```json  
  "dependencies": {
    "request": "^2.88.2"
  }
```

You would get this by running `npm add request` in the module directory. The `request` package is very common, yet, somebody may not have installed it and would probably run into issues. But I'm not sure. 

@lordvalium this might be exactly your issue. Could you please try the following:
```
cd ~/MagicMirror/modules/MMM-DWD-Pollen
rm package.json # if you had made your own
git pull
npm install

# now restart the mirror and check if your reported error persists. If the error is still there continue with

npm add request
npm install

# now restart the mirror and check if your error is fixed
```

Please report back if your error was solved and if so after which part of the steps above.

**Comment by carstendirks** [comment]
Thanks.
Added the dependency. I saw that others also added Electron as dependency but I guess I would leave this to MM installation.

**Comment by pinsdorf** [comment]
I'd close the issue as @carstendirks changes fixes it. Thanks for quick follow-up.
