### ISSUE TITLE
size of visible information

### ISSUE THREAD

**Issue by stefanlk** [carstendirks/MMM-DWD-Pollen#8]
the informations are shown on the total width.
can you shrink the visable informations to one region?
also can you make the header optional?
Thanks

**Comment by carstendirks** [comment]
Thanks for your feedback.
The header should be no problem.
Can you help me to understand the other 2 comments on brightness and the region? Maybe an example?

**Comment by stefanlk** [comment]
Hello,
excuse me, I wrote a wrong word brightness --> width :-)
I set the position to middle-center.
I wanted to see the table on the left side only.

Stefan
![WoZVvnSOHh9tUh3F](https://user-images.githubusercontent.com/32956179/158063383-1a29a540-d61f-41ea-9231-bea176707724.png)

**Comment by carstendirks** [comment]
I see. Thanks,
Have you tried this in custom.css?
Normally you can define the title in the custom.css like:
`.<modulename> .module-header {
  display: none;
}'

For the alignment you can override the  [MMM-DWD-Pollen.css] in the customer.css with the text-align: left

Let me know if this works, otherwise I would have to see how to make this a config parameter

**Comment by stefanlk** [comment]
Ok, thanks for the reply.
for the header: I didn't understand in details. I have not the time to experiment. Can you please test and post the right custom.css?
for the width: I tried, but it didn't worked. I also think the visible part shall be restricted to one region. In addition, can you look for a working result and post it here?
Thanks
Stefan

**Comment by carstendirks** [comment]
For removing the title just take out the "header" line in the config file.

**Comment by carstendirks** [comment]
For the width you can enter the following in your custom.css:
`
.module.MMM-DWD-Pollen {
max-width: 200px; // adjust px to taste, or use %, em, etc
}
`

Has to be outside the body(!)

I do not know how to restrict it to visible area

**Comment by carstendirks** [comment]
`.module.MMM-DWD-Pollen {
max-width: 200px; // adjust px to taste, or use %, em, etc
}

**Comment by stefanlk** [comment]
I changed the width to 50%.
Thanks it worked
